# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
    # branches:
    #     include: [ main ]
    # paths:
    #     include: [ "**.bicep", "azure-pipelines.yml" ]

variables:
  resourceGroupName: 'rg-DevOpsPipelines-australiaeast'
  deploymentDefaultLocation: 'australiaeast'
  templates: 1_main.bicep

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Lint

    jobs:
    - job: Lint
      displayName: 'Lint code'

      steps:
      - script: |
          files="$(build.sourcesDirectory)/*.bicep"
          for file in $files
          do
              echo "Checking file: '$file'"
              az bicep build --file $file
          done
        displayName: 'Lint each bicep file'

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Validate 1_main.bicep'
        inputs:
          connectedServiceName: 'AzureLab'
          location: $(deploymentDefaultLocation)
          deploymentMode: Validation
          resourceGroupName: $(resourceGroupName)
          csmFile: 1_main.bicep
